### ISSUE TITLE
Demo code threw this exception

### ISSUE THREAD

**Issue by fastboxster** [damienbod/AspNetCoreCsvImportExport#2]
System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'AspNetCoreCsvImportExport.Model.LocalizationRecord' to type 'System.Collections.IList'.
  Source=AspNetCoreCsvImportExport
  StackTrace:
       at AspNetCoreCsvImportExport.Formatters.CsvInputFormatter.readStream(Type type, Stream stream) in C:\projects\AspNetCoreCsvImportExport\AspNetCoreCsvImportExport-master\src\AspNetCoreCsvImportExport\Formatters\CsvInputFormatter.cs:line 71
       at AspNetCoreCsvImportExport.Formatters.CsvInputFormatter.ReadRequestBodyAsync(InputFormatterContext context) in C:\projects\AspNetCoreCsvImportExport\AspNetCoreCsvImportExport-master\src\AspNetCoreCsvImportExport\Formatters\CsvInputFormatter.cs:line 37
       at Microsoft.AspNetCore.Mvc.Formatters.InputFormatter.ReadAsync(InputFormatterContext context)
       at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinder.<BindModelAsync>d__3.MoveNext()
  InnerException:

**Comment by damienbod** [comment]
Thanks, I'll check this and merge your pull request next week.

Greetings Damien

**Comment by damienbod** [comment]
merged, thanks again.
